### ISSUE TITLE
OIDC Pkce

### ISSUE THREAD

**Issue by juanan** [openathens/keystoneconnector#1]
Hi,

do you support code authorization flow with Pkce in a .Net Framework 4.7.2 ASPNET app?

Many thanks.

**Comment by oajulianclementson** [comment]
Hi @juanan 

No, this repo is forked from the Microsoft Katana project which doesn't support PKCE. We have added support for the authorization code flow, but not PKCE. This repo was designed specifically to add support for the OpenAthens service, but that service doesn't support PKCE.

Regards
